# Generated by Django 5.1.7 on 2025-03-20 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'permissions': [('can_unpublish_product', 'Can unpublish product'), ('can_delete_blog', 'Can delete blog')], 'verbose_name': 'Блоговая запись', 'verbose_name_plural': 'Блоговые записи'},
        ),
    ]
