# Generated by Django 5.1.7 on 2025-03-26 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_product_view_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='view_count',
            new_name='views_count',
        ),
    ]
